package com.cimen.ways.component.authentication.service.launcher.model;

import com.cimen.ways.component.dal.domains.BaseModel;

import java.io.Serializable;
import java.util.Date;

public class OauthClientDetails implements BaseModel,Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : oauth_client_details.id
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * client_id
     * 表字段 : oauth_client_details.client_id
     * </pre>
     */
    private String clientId;

    /**
     * <pre>
     * resource_ids
     * 表字段 : oauth_client_details.resource_ids
     * </pre>
     */
    private String resourceIds;

    /**
     * <pre>
     * 密钥明文
     * 表字段 : oauth_client_details.client_secret_plain_text
     * </pre>
     */
    private String clientSecretPlainText;

    /**
     * <pre>
     * client_secret
     * 表字段 : oauth_client_details.client_secret
     * </pre>
     */
    private String clientSecret;

    /**
     * <pre>
     * 授权范围
     * 表字段 : oauth_client_details.scope
     * </pre>
     */
    private String scope;

    /**
     * <pre>
     * 授权类型
     * 表字段 : oauth_client_details.authorized_grant_types
     * </pre>
     */
    private String authorizedGrantTypes;

    /**
     * <pre>
     * 
     * 表字段 : oauth_client_details.web_server_redirect_uri
     * </pre>
     */
    private String webServerRedirectUri;

    /**
     * <pre>
     * 
     * 表字段 : oauth_client_details.authorities
     * </pre>
     */
    private String authorities;

    /**
     * <pre>
     * access_token有效时间
     * 表字段 : oauth_client_details.access_token_validity
     * </pre>
     */
    private String accessTokenValidity;

    /**
     * <pre>
     * refresh_token有效时间
     * 表字段 : oauth_client_details.refresh_token_validity
     * </pre>
     */
    private String refreshTokenValidity;

    /**
     * <pre>
     * 
     * 表字段 : oauth_client_details.additional_information
     * </pre>
     */
    private String additionalInformation;

    /**
     * <pre>
     * 
     * 表字段 : oauth_client_details.autoapprove
     * </pre>
     */
    private String autoapprove;

    /**
     * <pre>
     * 创建人
     * 表字段 : oauth_client_details.creator
     * </pre>
     */
    private String creator;

    /**
     * <pre>
     * 创建时间
     * 表字段 : oauth_client_details.create_date
     * </pre>
     */
    private Date createDate;

    /**
     * <pre>
     * 修改人
     * 表字段 : oauth_client_details.modifier
     * </pre>
     */
    private String modifier;

    /**
     * <pre>
     * 修改时间
     * 表字段 : oauth_client_details.modify_date
     * </pre>
     */
    private Date modifyDate;

    /**
     * <pre>
     * 删除标记
     * 表字段 : oauth_client_details.del_flag
     * </pre>
     */
    private Byte delFlag;

    /**
     * <pre>
     * 系统编号
     * 表字段 : oauth_client_details.application_code
     * </pre>
     */
    private String applicationCode;

    /**
     * <pre>
     * 租户编号
     * 表字段 : oauth_client_details.tenant_code
     * </pre>
     */
    private String tenantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * Auto-Generator
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：主键
     * 表字段：oauth_client_details.id
     * </pre>
     *
     * @return oauth_client_details.id：主键
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * 设置：主键
     * 表字段：oauth_client_details.id
     * </pre>
     *
     * @param id
     *            oauth_client_details.id：主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * 获取：client_id
     * 表字段：oauth_client_details.client_id
     * </pre>
     *
     * @return oauth_client_details.client_id：client_id
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * <pre>
     * 设置：client_id
     * 表字段：oauth_client_details.client_id
     * </pre>
     *
     * @param clientId
     *            oauth_client_details.client_id：client_id
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * <pre>
     * 获取：resource_ids
     * 表字段：oauth_client_details.resource_ids
     * </pre>
     *
     * @return oauth_client_details.resource_ids：resource_ids
     */
    public String getResourceIds() {
        return resourceIds;
    }

    /**
     * <pre>
     * 设置：resource_ids
     * 表字段：oauth_client_details.resource_ids
     * </pre>
     *
     * @param resourceIds
     *            oauth_client_details.resource_ids：resource_ids
     */
    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds == null ? null : resourceIds.trim();
    }

    /**
     * <pre>
     * 获取：密钥明文
     * 表字段：oauth_client_details.client_secret_plain_text
     * </pre>
     *
     * @return oauth_client_details.client_secret_plain_text：密钥明文
     */
    public String getClientSecretPlainText() {
        return clientSecretPlainText;
    }

    /**
     * <pre>
     * 设置：密钥明文
     * 表字段：oauth_client_details.client_secret_plain_text
     * </pre>
     *
     * @param clientSecretPlainText
     *            oauth_client_details.client_secret_plain_text：密钥明文
     */
    public void setClientSecretPlainText(String clientSecretPlainText) {
        this.clientSecretPlainText = clientSecretPlainText == null ? null : clientSecretPlainText.trim();
    }

    /**
     * <pre>
     * 获取：client_secret
     * 表字段：oauth_client_details.client_secret
     * </pre>
     *
     * @return oauth_client_details.client_secret：client_secret
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * <pre>
     * 设置：client_secret
     * 表字段：oauth_client_details.client_secret
     * </pre>
     *
     * @param clientSecret
     *            oauth_client_details.client_secret：client_secret
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * <pre>
     * 获取：授权范围
     * 表字段：oauth_client_details.scope
     * </pre>
     *
     * @return oauth_client_details.scope：授权范围
     */
    public String getScope() {
        return scope;
    }

    /**
     * <pre>
     * 设置：授权范围
     * 表字段：oauth_client_details.scope
     * </pre>
     *
     * @param scope
     *            oauth_client_details.scope：授权范围
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * <pre>
     * 获取：授权类型
     * 表字段：oauth_client_details.authorized_grant_types
     * </pre>
     *
     * @return oauth_client_details.authorized_grant_types：授权类型
     */
    public String getAuthorizedGrantTypes() {
        return authorizedGrantTypes;
    }

    /**
     * <pre>
     * 设置：授权类型
     * 表字段：oauth_client_details.authorized_grant_types
     * </pre>
     *
     * @param authorizedGrantTypes
     *            oauth_client_details.authorized_grant_types：授权类型
     */
    public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
        this.authorizedGrantTypes = authorizedGrantTypes == null ? null : authorizedGrantTypes.trim();
    }

    /**
     * <pre>
     * 获取：
     * 表字段：oauth_client_details.web_server_redirect_uri
     * </pre>
     *
     * @return oauth_client_details.web_server_redirect_uri：
     */
    public String getWebServerRedirectUri() {
        return webServerRedirectUri;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：oauth_client_details.web_server_redirect_uri
     * </pre>
     *
     * @param webServerRedirectUri
     *            oauth_client_details.web_server_redirect_uri：
     */
    public void setWebServerRedirectUri(String webServerRedirectUri) {
        this.webServerRedirectUri = webServerRedirectUri == null ? null : webServerRedirectUri.trim();
    }

    /**
     * <pre>
     * 获取：
     * 表字段：oauth_client_details.authorities
     * </pre>
     *
     * @return oauth_client_details.authorities：
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：oauth_client_details.authorities
     * </pre>
     *
     * @param authorities
     *            oauth_client_details.authorities：
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities == null ? null : authorities.trim();
    }

    /**
     * <pre>
     * 获取：access_token有效时间
     * 表字段：oauth_client_details.access_token_validity
     * </pre>
     *
     * @return oauth_client_details.access_token_validity：access_token有效时间
     */
    public String getAccessTokenValidity() {
        return accessTokenValidity;
    }

    /**
     * <pre>
     * 设置：access_token有效时间
     * 表字段：oauth_client_details.access_token_validity
     * </pre>
     *
     * @param accessTokenValidity
     *            oauth_client_details.access_token_validity：access_token有效时间
     */
    public void setAccessTokenValidity(String accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity == null ? null : accessTokenValidity.trim();
    }

    /**
     * <pre>
     * 获取：refresh_token有效时间
     * 表字段：oauth_client_details.refresh_token_validity
     * </pre>
     *
     * @return oauth_client_details.refresh_token_validity：refresh_token有效时间
     */
    public String getRefreshTokenValidity() {
        return refreshTokenValidity;
    }

    /**
     * <pre>
     * 设置：refresh_token有效时间
     * 表字段：oauth_client_details.refresh_token_validity
     * </pre>
     *
     * @param refreshTokenValidity
     *            oauth_client_details.refresh_token_validity：refresh_token有效时间
     */
    public void setRefreshTokenValidity(String refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity == null ? null : refreshTokenValidity.trim();
    }

    /**
     * <pre>
     * 获取：
     * 表字段：oauth_client_details.additional_information
     * </pre>
     *
     * @return oauth_client_details.additional_information：
     */
    public String getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：oauth_client_details.additional_information
     * </pre>
     *
     * @param additionalInformation
     *            oauth_client_details.additional_information：
     */
    public void setAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation == null ? null : additionalInformation.trim();
    }

    /**
     * <pre>
     * 获取：
     * 表字段：oauth_client_details.autoapprove
     * </pre>
     *
     * @return oauth_client_details.autoapprove：
     */
    public String getAutoapprove() {
        return autoapprove;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：oauth_client_details.autoapprove
     * </pre>
     *
     * @param autoapprove
     *            oauth_client_details.autoapprove：
     */
    public void setAutoapprove(String autoapprove) {
        this.autoapprove = autoapprove == null ? null : autoapprove.trim();
    }

    /**
     * <pre>
     * 获取：创建人
     * 表字段：oauth_client_details.creator
     * </pre>
     *
     * @return oauth_client_details.creator：创建人
     */
    public String getCreator() {
        return creator;
    }

    /**
     * <pre>
     * 设置：创建人
     * 表字段：oauth_client_details.creator
     * </pre>
     *
     * @param creator
     *            oauth_client_details.creator：创建人
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * <pre>
     * 获取：创建时间
     * 表字段：oauth_client_details.create_date
     * </pre>
     *
     * @return oauth_client_details.create_date：创建时间
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * <pre>
     * 设置：创建时间
     * 表字段：oauth_client_details.create_date
     * </pre>
     *
     * @param createDate
     *            oauth_client_details.create_date：创建时间
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * <pre>
     * 获取：修改人
     * 表字段：oauth_client_details.modifier
     * </pre>
     *
     * @return oauth_client_details.modifier：修改人
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * <pre>
     * 设置：修改人
     * 表字段：oauth_client_details.modifier
     * </pre>
     *
     * @param modifier
     *            oauth_client_details.modifier：修改人
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * <pre>
     * 获取：修改时间
     * 表字段：oauth_client_details.modify_date
     * </pre>
     *
     * @return oauth_client_details.modify_date：修改时间
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * <pre>
     * 设置：修改时间
     * 表字段：oauth_client_details.modify_date
     * </pre>
     *
     * @param modifyDate
     *            oauth_client_details.modify_date：修改时间
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * <pre>
     * 获取：删除标记
     * 表字段：oauth_client_details.del_flag
     * </pre>
     *
     * @return oauth_client_details.del_flag：删除标记
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * <pre>
     * 设置：删除标记
     * 表字段：oauth_client_details.del_flag
     * </pre>
     *
     * @param delFlag
     *            oauth_client_details.del_flag：删除标记
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * <pre>
     * 获取：系统编号
     * 表字段：oauth_client_details.application_code
     * </pre>
     *
     * @return oauth_client_details.application_code：系统编号
     */
    public String getApplicationCode() {
        return applicationCode;
    }

    /**
     * <pre>
     * 设置：系统编号
     * 表字段：oauth_client_details.application_code
     * </pre>
     *
     * @param applicationCode
     *            oauth_client_details.application_code：系统编号
     */
    public void setApplicationCode(String applicationCode) {
        this.applicationCode = applicationCode == null ? null : applicationCode.trim();
    }

    /**
     * <pre>
     * 获取：租户编号
     * 表字段：oauth_client_details.tenant_code
     * </pre>
     *
     * @return oauth_client_details.tenant_code：租户编号
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * <pre>
     * 设置：租户编号
     * 表字段：oauth_client_details.tenant_code
     * </pre>
     *
     * @param tenantCode
     *            oauth_client_details.tenant_code：租户编号
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode == null ? null : tenantCode.trim();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthClientDetails other = (OauthClientDetails) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getResourceIds() == null ? other.getResourceIds() == null : this.getResourceIds().equals(other.getResourceIds()))
            && (this.getClientSecretPlainText() == null ? other.getClientSecretPlainText() == null : this.getClientSecretPlainText().equals(other.getClientSecretPlainText()))
            && (this.getClientSecret() == null ? other.getClientSecret() == null : this.getClientSecret().equals(other.getClientSecret()))
            && (this.getScope() == null ? other.getScope() == null : this.getScope().equals(other.getScope()))
            && (this.getAuthorizedGrantTypes() == null ? other.getAuthorizedGrantTypes() == null : this.getAuthorizedGrantTypes().equals(other.getAuthorizedGrantTypes()))
            && (this.getWebServerRedirectUri() == null ? other.getWebServerRedirectUri() == null : this.getWebServerRedirectUri().equals(other.getWebServerRedirectUri()))
            && (this.getAuthorities() == null ? other.getAuthorities() == null : this.getAuthorities().equals(other.getAuthorities()))
            && (this.getAccessTokenValidity() == null ? other.getAccessTokenValidity() == null : this.getAccessTokenValidity().equals(other.getAccessTokenValidity()))
            && (this.getRefreshTokenValidity() == null ? other.getRefreshTokenValidity() == null : this.getRefreshTokenValidity().equals(other.getRefreshTokenValidity()))
            && (this.getAdditionalInformation() == null ? other.getAdditionalInformation() == null : this.getAdditionalInformation().equals(other.getAdditionalInformation()))
            && (this.getAutoapprove() == null ? other.getAutoapprove() == null : this.getAutoapprove().equals(other.getAutoapprove()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getApplicationCode() == null ? other.getApplicationCode() == null : this.getApplicationCode().equals(other.getApplicationCode()))
            && (this.getTenantCode() == null ? other.getTenantCode() == null : this.getTenantCode().equals(other.getTenantCode()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getResourceIds() == null) ? 0 : getResourceIds().hashCode());
        result = prime * result + ((getClientSecretPlainText() == null) ? 0 : getClientSecretPlainText().hashCode());
        result = prime * result + ((getClientSecret() == null) ? 0 : getClientSecret().hashCode());
        result = prime * result + ((getScope() == null) ? 0 : getScope().hashCode());
        result = prime * result + ((getAuthorizedGrantTypes() == null) ? 0 : getAuthorizedGrantTypes().hashCode());
        result = prime * result + ((getWebServerRedirectUri() == null) ? 0 : getWebServerRedirectUri().hashCode());
        result = prime * result + ((getAuthorities() == null) ? 0 : getAuthorities().hashCode());
        result = prime * result + ((getAccessTokenValidity() == null) ? 0 : getAccessTokenValidity().hashCode());
        result = prime * result + ((getRefreshTokenValidity() == null) ? 0 : getRefreshTokenValidity().hashCode());
        result = prime * result + ((getAdditionalInformation() == null) ? 0 : getAdditionalInformation().hashCode());
        result = prime * result + ((getAutoapprove() == null) ? 0 : getAutoapprove().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getApplicationCode() == null) ? 0 : getApplicationCode().hashCode());
        result = prime * result + ((getTenantCode() == null) ? 0 : getTenantCode().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", clientId=").append(clientId);
        sb.append(", resourceIds=").append(resourceIds);
        sb.append(", clientSecretPlainText=").append(clientSecretPlainText);
        sb.append(", clientSecret=").append(clientSecret);
        sb.append(", scope=").append(scope);
        sb.append(", authorizedGrantTypes=").append(authorizedGrantTypes);
        sb.append(", webServerRedirectUri=").append(webServerRedirectUri);
        sb.append(", authorities=").append(authorities);
        sb.append(", accessTokenValidity=").append(accessTokenValidity);
        sb.append(", refreshTokenValidity=").append(refreshTokenValidity);
        sb.append(", additionalInformation=").append(additionalInformation);
        sb.append(", autoapprove=").append(autoapprove);
        sb.append(", creator=").append(creator);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", applicationCode=").append(applicationCode);
        sb.append(", tenantCode=").append(tenantCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}